packages:
  - 'auth-service'
  - 'item-service'
  - 'orders-service'
  - 'kitchen-service'
  - 'rider-service'
  - 'frontend'

nodeLinker: hoisted

allowBuilds:
  '@parcel/watcher': true
  '@scarf/scarf': false
  bcrypt: true
  esbuild: true
  unrs-resolver: true
